apiVersion: v1
kind: Service
metadata:
  name: servicemesh
  labels:
    name: servicemesh
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: servicemesh
  type: ClusterIP