apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-virtualservice
  namespace: istio-system
spec:
  hosts:
    - "*"
  gateways:
    - my-gateway
  http:
    - match:
        - uri:
            prefix: /servicemesh
      route:
        - destination:
            host: servicemesh
            port: 
              number: 3198
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: nginx
            port: 
              number: 8080